language: python
sudo: 
- required

install:
- pip install requests[security]
- pip install pandoc
- apt-get install rsync
- apt-get install pandoc

global_env: 
- ENCRYPTION_LABEL=d7e0dc08b1d8 COMMIT_AUTHOR_EMAIL=sgeorgiou@aueb.gr

script: 
- bash tools/travis-deploy.sh

